export default [
  {
    id: 1,
    title: "Senior Product Designers",
    experience: "2 yrs",
    salary: "$80 - $120K/ year",
    companyName: "InVision",
    location: "Remote",
    icon: "invision",
    role: 1,
    isFavorite: true,
  },
  {
    id: 2,
    title: "UI/UX Designers",
    experience: "3 yrs",
    salary: "$120 - $160K/ year",
    companyName: "Notion",
    location: "San Francisco",
    icon: "notion",
    role: 2,
    isFavorite: false,
  },
  {
    id: 3,
    title: "Junior Product Designer",
    experience: "1 yrs",
    salary: "$70 - $100K/ year",
    companyName: "SnapChat",
    location: "San Francisco",
    icon: "snapchat",
    role: 1,
    isFavorite: false,
  },
  {
    id: 4,
    title: "Visual & Product Designers",
    experience: "2 yrs",
    salary: "$80 - $120K/ year",
    companyName: "InVision",
    location: "Remote",
    icon: "invision",
    role: 1,
    isFavorite: false,
  },
  {
    id: 5,
    title: "Mobile Developer",
    experience: "3 yrs",
    salary: "$90 - $125K/ year",
    companyName: "InVision",
    location: "Remote",
    icon: "invision",
    role: 3,
    isFavorite: false,
  },
  {
    id: 6,
    title: "Senior React JS",
    experience: "5 yrs",
    salary: "$110 - $140K/ year",
    companyName: "SnapChat",
    location: "San Francisco",
    icon: "snapchat",
    role: 5,
    isFavorite: false,
  },
  {
    id: 7,
    title: "Back end",
    experience: "3 yrs",
    salary: "$90 - $110K/ year",
    companyName: "Notion",
    location: "San Francisco",
    icon: "notion",
    role: 6,
    isFavorite: false,
  },
];
