export default [
  
  {
    id: 1,
    title: "UI/UX Designers",
    experience: "3 yrs",
    salary: "$120 - $160K/ year",
    companyName: "Notion",
    location: "San Francisco",
    address: "2300 Harrison Street , San Francisco",
    icon: "notion",
    role: 2,
    isFavorite: false,
    toLoc: {
      latitude: 37.7602363,
      longitude: -122.413467,
    },
  },
  {
    id: 2,
    title: "Senior Product Designers",
    experience: "2 yrs",
    salary: "$80 - $120K/ year",
    companyName: "InVision",
    location: "Remote",
    address: "28 W. 44th Street, New York",
    icon: "invision",
    role: 1,
    isFavorite: true,
    toLoc: {
      latitude: 40.7423375,
      longitude: -73.9879508,
    },
  },
  {
    id: 3,
    title: "Junior Product Designer",
    experience: "1 yrs",
    salary: "$70 - $100K/ year",
    companyName: "SnapChat",
    location: "Santa Monica",
    address: "Santa Monica, 2772 Donald Douglas Loop N, United States",
    icon: "snapchat",
    role: 1,
    isFavorite: false,
    toLoc: {
      latitude: 34.0160185,
      longitude: -118.4543987,
    },
  },
  {
    id: 4,
    title: "Visual & Product Designers",
    experience: "2 yrs",
    salary: "$80 - $120K/ year",
    companyName: "InVision",
    location: "Remote",
    address: "28 W. 44th Street, New York",
    icon: "invision",
    role: 1,
    isFavorite: false,
    toLoc: {
      latitude: 40.7423375,
      longitude: -73.9879508,
    },
  },
  {
    id: 5,
    title: "Mobile Developer",
    experience: "3 yrs",
    salary: "$90 - $125K/ year",
    companyName: "InVision",
    location: "Remote",
    address: "28 W. 44th Street, New York",
    icon: "invision",
    role: 3,
    isFavorite: false,
    toLoc: {
      latitude: 40.7423375,
      longitude: -73.9879508,
    },
  },
  {
    id: 6,
    title: "Senior React JS",
    experience: "5 yrs",
    salary: "$110 - $140K/ year",
    companyName: "SnapChat",
    location: "Santa Monica",
    address: "Santa Monica, 2772 Donald Douglas Loop N, United States",
    icon: "snapchat",
    role: 5,
    isFavorite: false,
    toLoc: {
      latitude: 34.0160185,
      longitude: -118.4543987,
    },
  },
  {
    id: 7,
    title: "Back end",
    experience: "3 yrs",
    salary: "$90 - $110K/ year",
    companyName: "Notion",
    location: "San Francisco",
    address: "2300 Harrison Street , San Francisco",
    icon: "notion",
    role: 6,
    isFavorite: false,
    toLoc: {
      latitude: 37.7602363,
      longitude: -122.413467,
    },
  },
];
